preserve_hierarchy: true
commit_message: '[ci skip]'

files:
  - source: apps/frontend/src/locales/en-US/*
    dest: /frontend/%original_file_name%
    translation: apps/frontend/src/locales/%locale%/%original_file_name%
  - source: packages/ui/src/locales/en-US/*
    dest: /ui/%original_file_name%
    translation: packages/ui/src/locales/%locale%/%original_file_name%

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
